# Generated by Django 4.0.3 on 2022-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeDataSan', '0003_auto_20220330_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crimeposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
