# Generated by Django 4.0.3 on 2022-03-30 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CrimeDataSan', '0004_alter_crimedate_id_alter_crimeposition_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Visitor',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='visitor',
        ),
    ]
